[build]
  publish = "public"
  command = "npm run build"

[context.production.environment]
  HUGO_VERSION = "0.68.3"
  HUGO_ENV = "production"
  HUGO_ENABLEGITINFO = "true"

[[redirects]]
  from = "https://xuezenghui.netlify.com/*"
  to = "https://xuezenghui.com/:splat"
  force = true