[build]
  publish = "public"
  command = "npm run build"

[context.production.environment]
  HUGO_VERSION = "0.63.0"
  HUGO_ENV = "production"
  HUGO_ENABLEGITINFO = "true"

[[redirects]]
  from = "https://xuezenghui.netlify.com/*"
  to = "https://xuezenghui.com/:splat"
  force = true